# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e9d53201c4b45aca46cff7e65ed514222b6da0ecbaa4af90a9febe2f32e8e3fd2ac29521fbe47f9088a6b026716511c9d3de6e02999751ae18bcbc50d1cbb0

test:
  secret_key_base: fc3247d42f1b0f261933c005f6a575cb5fde75006b63a7cefb09f0f54ddbbc076b2e3824bb6481bba38ab1435d1b6beb94faed27a4d789b5c464c1fbf44e16e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
